apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: mslab  # Especifique o namespace aqui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-teste
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx:latest
        ports:
        - containerPort: 80
