apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: mslab  # Especifique o namespace correto aqui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-test  # Esta label deve corresponder à label do template abaixo
  template:
    metadata:
      labels:
        app: my-app-test  # As labels do template devem corresponder ao selector
    spec:
      containers:
      - name: my-container
        image: nginx:latest
        ports:
        - containerPort: 80
