name: Deploy to Kind

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kind
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: v0.17.0

    - name: Create a Kind cluster
      run: kind create cluster --name mouralab-dev --wait 5m

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.24.0'

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f kind/namespace.yaml  # Cria o namespace se não existir
        kubectl apply -f kind/deployment.yaml
        kubectl apply -f kind/service.yaml

    - name: Verify deployment
      run: kubectl get pods